# Makefile

# Define the 'all' rule that runs when 'make' is invoked without any arguments.
all: install run

install:
	pip install pandas numpy matplotlib seaborn scikit-learn scipy mlxtend markdown tabulate

run:
	python3 index.py
